# **Phase 3: Data Cleaning**

In [3]:
# Loading file in Python for cleaning.
import pandas as pd
df = pd.read_csv('Churn_Modelling_for_Cleaning.csv')
df.head()

,Unnamed: 0,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
# Removing columns that do not contribute to churn behavior
df_clean = df.drop(['Unnamed: 0', 'RowNumber', 'CustomerId', 'Surname'], axis=1)
# Checking the first few rows of the cleaned data
df_clean.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# Checking data types for all columns.
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

## **Data Cleaning & Refinement**
In this phase, we refined the raw dataset to ensure it is optimized for exploratory analysis.
## 1. Feature Selection (Removing Noise)
* **Action:** We dropped the following columns: `RowNumber`, `CustomerId`, and `Surname`.
* **Business Rationale:** These columns are personal identifiers or system-generated indices. Since they do not possess any predictive power regarding a customer's decision to leave the bank, removing them reduces the dimensionality of our data and prevents `overfitting` during analysis.
## 2. Handling Indexing Artifacts
* **Action:** Removed the Unnamed: 0 column which appeared to be a remnant of a previous CSV save operation.
## 3. Validation of Data Types
* **Status:** Performed a check on column formats. All critical metrics such as `CreditScore`, `Balance`, and `Age` are correctly identified as `numerical (int/float)`, ensuring that mathematical operations in the EDA phase will be accurate.

In [10]:
# Saving data in file for future use.
df.to_csv('cleaned_dataset_for_EDA.csv', index=False)
print('File has been saved successfully.')

File has been saved successfully.